name: build

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create some files
        run: |
          echo "foo" > foo.txt
          echo "bar" > bar.txt
          mkdir subdir && cd subdir
          echo "subfoo" > sfoo.txt
          echo "subbar" > sbar.txt
      
      - uses: actions/upload-artifact@v3
        with:
          name: build-output.${{ github.run_number }}
          path: |
            **/*.txt

  stage2:
    needs: stage1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create some files
        run: |
          echo "foo" > foo.txt
          echo "bar" > bar.txt
          mkdir subdir && cd subdir
          echo "subfoo" > sfoo.txt
          echo "subbar" > sbar.txt
      
      - uses: actions/download-artifact@v3
        with:
          name: build-output.${{ github.run_number }}

      - name: List
        run: ls -laR
